### ISSUE TITLE
Dont Work

### ISSUE THREAD

**Issue by Zorky251** [DW8030/Modern-Civilizations#1]
Cannibal's unique "May upgrade to [Spearman] through ruins-like effects" contains parameter Spearman, which does not fit parameter type baseUnitFilter !
Voortrekker's unique "Can build [Farm] improvements on tiles" contains parameter Farm, which does not fit parameter type improvementFilter or terrainFilter !
Maple Farm's unique "[+2 Gold] from [Forest] tiles [in this city]" contains parameter Forest, which does not fit parameter type tileFilter !
Maple Farm's unique "Must have an owned [Forest] within [2] tiles" contains parameter Forest, which does not fit parameter type tileFilter !
Statue's unique "[+15]% Production when constructing [Siege] units [in this city]" contains parameter Siege, which does not fit parameter type baseUnitFilter !
Statue's unique "[+15]% Production when constructing [Atomic Bomb] units [in this city]" contains parameter Atomic Bomb, which does not fit parameter type baseUnitFilter !
Statue's unique "[+15]% Production when constructing [Nuclear Missile] units [in this city]" contains parameter Nuclear Missile, which does not fit parameter type baseUnitFilter !
Sauna's unique "[+2 Food] from [Camp] tiles [in this city]" contains parameter Camp, which does not fit parameter type tileFilter !
Sauna's unique "Must be next to [Tundra]" contains parameter Tundra, which does not fit parameter type tileFilter !
Treehouse's unique "[+1 Food] from [Jungle] tiles [in this city] <during a Golden Age>" contains parameter Jungle, which does not fit parameter type tileFilter !
Treehouse's unique "Must have an owned [Jungle] within [2] tiles" contains parameter Jungle, which does not fit parameter type tileFilter !
Chaebol's unique "[+4 Production] from [Manufactory] tiles [in this city]" contains parameter Manufactory, which does not fit parameter type tileFilter !
Chaebol's unique "[+4 Gold] from [Customs house] tiles [in this city]" contains parameter Customs house, which does not fit parameter type tileFilter !
Chaebol's unique "[+4 Science] from [Academy] tiles [in this city]" contains parameter Academy, which does not fit parameter type tileFilter !
Chaebol's unique "[+4 Culture] from [Landmark] tiles [in this city]" contains parameter Landmark, which does not fit parameter type tileFilter !
Chaebol's unique "[+4 Faith] from [Holy site] tiles [in this city]" contains parameter Holy site, which does not fit parameter type tileFilter !
Chaebol's unique "Must be next to [Coast]" contains parameter Coast, which does not fit parameter type tileFilter !
Sheep Farm's unique "[+2 Gold] from [Sheep] tiles [in this city]" contains parameter Sheep, which does not fit parameter type tileFilter !
Whale Watching Resort's unique "[+4 Gold, +2 Culture] from [Whales] tiles [in this city]" contains parameter Whales, which does not fit parameter type tileFilter !
Whale Watching Resort's unique "Must be next to [Coast]" contains parameter Coast, which does not fit parameter type tileFilter !
Cosmodrome's unique "[+100]% Production when constructing [Spaceship part] units [in this city]" contains parameter Spaceship part, which does not fit parameter type baseUnitFilter !
Painted Church's unique "[+1 Culture, +1 Faith] from [Wine] tiles [in this city]" contains parameter Wine, which does not fit parameter type tileFilter !
Painted Church's unique "[+1 Culture, +1 Faith] from [Incense] tiles [in this city]" contains parameter Incense, which does not fit parameter type tileFilter !
Safari Park's unique "[+3 Gold, +3 Culture] from [Camp] tiles [in this city]" contains parameter Camp, which does not fit parameter type tileFilter !
Oil Facility's unique "Must be next to [Desert]" contains parameter Desert, which does not fit parameter type tileFilter !
Oil Facility's unique "[+3 Production, +3 Gold] from [Oil well] tiles [in this city]" contains parameter Oil well, which does not fit parameter type tileFilter !
Research Station's unique "[+2 Science] from [Snow] tiles [in this city]" contains parameter Snow, which does not fit parameter type tileFilter !
Research Station's unique "[+2 Science] from [Jungle] tiles [in this city]" contains parameter Jungle, which does not fit parameter type tileFilter !
Canada's unique "[+1 Culture] from every [Tundra]" contains parameter Tundra, which does not fit parameter type tileFilter or specialist or buildingFilter !
Switserland's unique "Land units may cross [Mountain] tiles after the first [Great Engineer] is earned" contains parameter Great Engineer, which does not fit parameter type baseUnitFilter !
North Korea's unique "Double quantity of [Uranium] produced" contains parameter Uranium, which does not fit parameter type resource !
Finland's unique "[+2 Culture] from every [Lakes]" contains parameter Lakes, which does not fit parameter type tileFilter or specialist or buildingFilter !
Saudi Arabia's unique "[+2 Faith] from every [Oasis]" contains parameter Oasis, which does not fit parameter type tileFilter or specialist or buildingFilter !
Papua's unique "No Maintenance costs for improvements in [Forest] tiles" contains parameter Forest, which does not fit parameter type tileFilter !
Papua's unique "No Maintenance costs for improvements in [Jungle] tiles" contains parameter Jungle, which does not fit parameter type tileFilter !
Papua's unique "[Land] units gain the [Woodsman] promotion" contains parameter Woodsman, which does not fit parameter type promotion !
Italy's unique "[+2 Culture] from every [Scientist] <during a Golden Age>" contains parameter Scientist, which does not fit parameter type tileFilter or specialist or buildingFilter !
Italy's unique "[+2 Science] from every [Artist] <during a Golden Age>" contains parameter Artist, which does not fit parameter type tileFilter or specialist or buildingFilter !
New Zealand's unique "[+1 Culture] from every [Forest] <while the empire is happy>" contains parameter Forest, which does not fit parameter type tileFilter or specialist or buildingFilter !
Singapore's unique "Cannot build [Settler] units" contains parameter Settler, which does not fit parameter type baseUnitFilter !
Kazakhstan's unique "Double quantity of [Coal] produced" contains parameter Coal, which does not fit parameter type resource !
Czechia's unique "[+1 Culture, +1 Science] from every [Water Mill]" contains parameter Water Mill, which does not fit parameter type tileFilter or specialist or buildingFilter !
Czechia's unique "[+1 Culture, +1 Science] from every [Garden]" contains parameter Garden, which does not fit parameter type tileFilter or specialist or buildingFilter !
Ukraine's unique "[+2 Gold] from every [Wheat]" contains parameter Wheat, which does not fit parameter type tileFilter or specialist or buildingFilter !
Ukraine's unique "Double quantity of [Horses] produced" contains parameter Horses, which does not fit parameter type resource !
South Africa's unique "[+100]% [Gold] from every [Gold Ore]" contains parameter Gold Ore, which does not fit parameter type tileFilter or buildingFilter !
South Africa's unique "[+100]% [Gold] from every [Silver]" contains parameter Silver, which does not fit parameter type tileFilter or buildingFilter !
South Africa's unique "[+100]% [Gold] from every [Gems]" contains parameter Gems, which does not fit parameter type tileFilter or buildingFilter !
South Africa's unique "Double quantity of [Gold Ore] produced" contains parameter Gold Ore, which does not fit parameter type resource !
South Africa's unique "Double quantity of [Silver] produced" contains parameter Silver, which does not fit parameter type resource !
South Africa's unique "Double quantity of [Gems] produced" contains parameter Gems, which does not fit parameter type resource !
Belgium's unique "[+1 Production] from every [Engineer]" contains parameter Engineer, which does not fit parameter type tileFilter or specialist or buildingFilter !
Belgium's unique "[+1 Gold] from every [Merchant]" contains parameter Merchant, which does not fit parameter type tileFilter or specialist or buildingFilter !
Belgium's unique "[+1 Science] from every [Scientist]" contains parameter Scientist, which does not fit parameter type tileFilter or specialist or buildingFilter !
Belgium's unique "[+1 Culture] from every [Artist]" contains parameter Artist, which does not fit parameter type tileFilter or specialist or buildingFilter !
Antarctica's unique "[+2 Food] from every [City center] <in [Snow] tiles>" contains parameter City center, which does not fit parameter type tileFilter or specialist or buildingFilter !
North Korea's colors do not contrast enough - it is unreadable!
Suggested colors: 
		"outerColor": [241, 84, 93],
		"innerColor": [1, 59, 121],
South Korea's colors do not contrast enough - it is unreadable!
Suggested colors: 
		"outerColor": [51, 184, 255],
		"innerColor": [164, 36, 46],
Kazakhstan's colors do not contrast enough - it is unreadable!
Suggested colors: 
		"outerColor": [0, 131, 151],
		"innerColor": [254, 211, 72],
Czechia's colors do not contrast enough - it is unreadable!
Suggested colors: 
		"outerColor": [12, 51, 94],
		"innerColor": [225, 78, 83],
Iran's colors do not contrast enough - it is unreadable!
Suggested colors: 
		"outerColor": [28, 127, 51],
		"innerColor": [254, 200, 81],
Turkiye's colors do not contrast enough - it is unreadable!
Suggested colors: 
		"outerColor": [73, 225, 210],
		"innerColor": [215, 9, 21],

**Comment by EmperorPinguin** [comment]
Does it help selecting G&K as ruleset?
